;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Movement.Dash_01",NewTagName="GA.Movement.Dash_01")
+GameplayTagRedirects=(OldTagName="Movement",NewTagName="GA.Movement")
+GameplayTagRedirects=(OldTagName="GA.Slot.Movement",NewTagName="GA.Slot.MovementAction")
+GameplayTagRedirects=(OldTagName="GA.FirePowers",NewTagName="GA.PowerFamily.Fire")
+GameplayTagRedirects=(OldTagName="GA.Telekinesis",NewTagName="GA.PowerFamily.Telekinesis")
+GameplayTagRedirects=(OldTagName="GA.Movement.Dash_01",NewTagName="GA.PowerFamily.Etheric.Dash_01")
+GameplayTagRedirects=(OldTagName="GA.Movement",NewTagName="GA.PowerFamily.Etheric")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Damage",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Hit",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="GA.Distance.ShootWeapon",DevComment="")
+GameplayTagList=(Tag="GA.Melee.Attack",DevComment="")
+GameplayTagList=(Tag="GA.PowerFamily.Etheric.Dash_01",DevComment="")
+GameplayTagList=(Tag="GA.PowerFamily.Etheric.Dash_01.Active",DevComment="")
+GameplayTagList=(Tag="GA.PowerFamily.Fire",DevComment="")
+GameplayTagList=(Tag="GA.PowerFamily.Telekinesis",DevComment="")
+GameplayTagList=(Tag="GA.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GA.Slot.ChargedAction",DevComment="")
+GameplayTagList=(Tag="GA.Slot.ChargedAction.Active",DevComment="")
+GameplayTagList=(Tag="GA.Slot.MovementAction",DevComment="")
+GameplayTagList=(Tag="GA.Slot.MovementAction.Active",DevComment="")
+GameplayTagList=(Tag="GA.Slot.PrimaryAction",DevComment="")
+GameplayTagList=(Tag="GA.Slot.PrimaryAction.Active",DevComment="")
+GameplayTagList=(Tag="GA.Slot.SecondaryAction",DevComment="")
+GameplayTagList=(Tag="GA.Slot.SecondaryAction.Active",DevComment="")
+GameplayTagList=(Tag="GA.Slot.UtilitaryAction",DevComment="")
+GameplayTagList=(Tag="GA.Slot.UtilitaryAction.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack.Main",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Movement.Teleportation",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.Bullet.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.Bullet.Custodian",DevComment="")
+GameplayTagList=(Tag="Melee",DevComment="")
+GameplayTagList=(Tag="Melee.ComboWindowClose",DevComment="")
+GameplayTagList=(Tag="Melee.ComboWindowOpen",DevComment="")
+GameplayTagList=(Tag="Melee.UnArmed.Punch.A01",DevComment="")
+GameplayTagList=(Tag="Skill.Melee.KnifeMastery",DevComment="")
+GameplayTagList=(Tag="Spell.Fireball",DevComment="")
+GameplayTagList=(Tag="Status.Health.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Baton.Blunt",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.TacticalKnife",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Custodian",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot.Ranged.Ammo",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot.Ranged.Barrel",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot.Ranged.Cross",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot.Ranged.Handle",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot.Ranged.Scope",DevComment="")

