;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Damage",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Hit",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="GA.Melee.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack.Main",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Movement.Teleportation",DevComment="")
+GameplayTagList=(Tag="Melee",DevComment="")
+GameplayTagList=(Tag="Melee.ComboWindowClose",DevComment="")
+GameplayTagList=(Tag="Melee.ComboWindowOpen",DevComment="")
+GameplayTagList=(Tag="Melee.UnArmed",DevComment="")
+GameplayTagList=(Tag="Melee.UnArmed.Punch",DevComment="")
+GameplayTagList=(Tag="Melee.UnArmed.Punch.A01",DevComment="")
+GameplayTagList=(Tag="Melee.UnArmed.Punch.A02",DevComment="")
+GameplayTagList=(Tag="Melee.UnArmed.Punch.A03",DevComment="")
+GameplayTagList=(Tag="Movement.Dash_01",DevComment="")
+GameplayTagList=(Tag="Skill.Melee.KnifeMastery",DevComment="")
+GameplayTagList=(Tag="Spell.Fireball",DevComment="")
+GameplayTagList=(Tag="Status.Health.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Baton.Blunt",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.TacticalKnife",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Custodian",DevComment="")

